### ISSUE TITLE
Caret don't move across tab-indented lines

### ISSUE THREAD

**Issue by maxkoryukov** [vsch/MissingInActions#17]
Thanks for this plugin!

My problem: selection does not move to prev/next **line**

Sample text:
```
	line 1 asdf
	word hello
```

**Tabs at the beggining of lines are required** to reproduce bug

I use "Ctrl + Shift + Left Arrow" for action "Move caret to previous start of word with selection" , but when a caret is on `e` in word `hello`, by pressing 'Ctrl + Shift + Left' I got selected:

1. `he`
2. `word he`
3. `word he`
4. ...

Expected behavior: 

3. step 3: multiline: 
    ```
    asdf
    word he
    ```
4. step 4: multiline, more words selected:
    ```
    1 asdf
    word he
    ```

**Comment by vsch** [comment]
@maxkoryukov, you can use the Custom version of the move and move with selection actions which allow you to customize on which boundaries these actions will stop:

![image](https://cloud.githubusercontent.com/assets/10299086/25784469/91582c88-333b-11e7-8922-790d8f0111df.png)

Key Map:

![image](https://cloud.githubusercontent.com/assets/10299086/25784471/aae4145a-333b-11e7-8f12-583b80a52ac1.png)

![image](https://cloud.githubusercontent.com/assets/10299086/25784472/b537285c-333b-11e7-81b6-7f53f3651226.png)

**Comment by maxkoryukov** [comment]
But when there is no `\t` at the beginning, or there are just `spaces` all works very good.

The best things works good _out of the box_ (IMO). If you think current behavior is good enough (for other reasons) - you are the owner :wink: !!

**Comment by vsch** [comment]
@maxkoryukov, the issue with the `\t` looks like a bug. I will get it fixed.

It is hard to make it work out of the box because of all the different systems and IDEs that it must support and not wanting to override user key maps without their consent. 

As for being the owner and knowing better, I would disagree. This is why I made the source available. Anyone can make improvements.

**Comment by vsch** [comment]
@maxkoryukov, fixed for next release. The code was not expanding leading tabs when figuring out caret position in next word code.

You can get the build with the fix here: https://github.com/vsch/MissingInActions/raw/master/dist/MissingInActions.1.3.4.zip

and install plugin from disk.

**Comment by maxkoryukov** [comment]
@vsch, sorry, but is seems, like IntelliJ has too much tiny annoying bugs/features, and brings too few enhancements to dev-process.

I am going to switch back to Sublime, because there all this stuff works like a charm. Yes, there a less "refactoring" tools, but Sublime doesn't eat 2000M of RAM and 2-4 GB (with updates) on the HDD. Probably, IntelliJ solutions are made not for me...

You could close this issue as soon as you wish;)

Thank you for your efforts!
