### ISSUE TITLE
Backspace to Word Start treats whitespace differently than Delete to Word End

### ISSUE THREAD

**Issue by todofixthis** [vsch/MissingInActions#2]
Example of Backspace to Word Start no EOL (`|` is caret):
```
# Before
test string with| spaces
            <---

# After
test string| spaces
           ^ space deleted
```

Example of Delete to Word End no EOL (`|` is caret):
```
# Before
test string |with spaces
             --->

# After
test string | spaces
             ^ space preserved
```

Note that the Backspace action deletes the leading space, but the Delete action stops at the trailing space.

**Comment by vsch** [comment]
@todofixthis, thank you for brining this up. I noticed it and it was bothering me but I made the functionality follow the IDE against my better judgement. I will fix this to be consistent to my liking:

* both backspace and delete should change behaviour according to their context. For example:

```
# Before
test string with| spaces

# After
test string| spaces
           ^ space deleted
```

```
# Before
test string with |spaces

# After
test string |spaces
            ^ space preserved
```

Example of Delete to Word End no EOL (`|` is caret):

```
# Before
test string |with spaces

# After
test string |spaces
             ^ space deleted
```

```
# Before
test string| with spaces

# After
test string| spaces
             ^ space preserved
```

That way it won't mess up the white space nor leave any extra.

What I am doing with this plugin is duplicating the text editing smarts I had in my editor. The IDEs are awesome for code smarts and they would have to pry them from my dead, cold hands, but when it comes to text editing smarts they lack the split and polish. This is where my plugin will excel.

**Comment by vsch** [comment]
@todofixthis, latest eap available from this repo has customization for delete/backspace keys which not only handles these keys in a symmetrical fashion  but also allows customization of what they delete via RegEx. See #18
