### ISSUE TITLE
FYI, installing plugin version < 1.4.20 causes display issues in all 2018.2 EAPs

### ISSUE THREAD

**Issue by dnedrow** [vsch/MissingInActions#20]
In case anyone is having an issue with toolbars and other decorators not showing after installing Missing In Actions, be sure to install 1.4.20+ to fix the issue.

**Comment by vsch** [comment]
@dnedrow, thanks. I think it is time to officially release the next version. 

I got busy and forgot that I only released the distribution zip in this repo.

**Comment by vsch** [comment]
@dnedrow, new version 1.5.0 released. It adds some improvements, bug fixes and Batch search/replace mode for multiple string search/replace.

**Comment by dnedrow** [comment]
@vsch , cool, thanks!
