### ISSUE TITLE
Clipboard history: ignore empty copy/paste entries (No characters, only whitespaces and line returns)

### ISSUE THREAD

**Issue by oxysoft** [vsch/MissingInActions#22]
I use CTRL-X a lot to strip lines, so my clipboard fills up with empty entries. This should apply only to the paste history window, CTRL-X should still copy to the clipboard, but not the history.

**Comment by vsch** [comment]
@oxysoft, that is a good option. I will add an option to keep only the latest blank clipboard content. By blank meaning whitespace characters only.

**Comment by vsch** [comment]
@oxysoft, added. Default is turned off so you need to enable it.

Fixed version is available in the repo [Download Latest 1.6.8 from this repo]

To install Download zip file. Do not extract the zip. Install by clicking "Install plugin from disk..." in the IDE under settings (preferences in OS X) under plugins and select the downloaded zip file.

[Download Latest 1.6.8 from this repo]: https://github.com/vsch/MissingInActions/blob/master/dist/MissingInActions.1.6.8.zip?raw=true

**Comment by oxysoft** [comment]
Excellent, looking forward to using this option.
