### ISSUE TITLE
i can haz build instructions pls 😇

### ISSUE THREAD

**Issue by todofixthis** [vsch/MissingInActions#30]
#29 seems [reasonably straightforward to fix](https://github.com/vsch/MissingInActions/issues/29#issuecomment-1119274865), so I set out this morning to see if I could fix it myself and submit a PR 😇

Unfortunately, I was not able to successfully get the project to build, primarily due to missing dependencies.  I managed to make some progress, but (likely due to my inexperience with Java/Kotlin and DevKit) I was unable to figure out how to get everything working.

If you could add build instructions to the repo, that would make it much easier for other devs to build + test the plugin and submit pull requests for enhancements and bugfixes 😺

**Comment by j-a-s-o-n-g** [comment]
@todofixthis Can you post the code fix to a fork without building it first? Do you think we can just extract the jar, make changes, and them re-jar it for a temporary fix?

**Comment by vsch** [comment]
**Uploaded new version which takes care of 2022 compatibility**, works with IJ 2022.1 and CLION 2022.3.2. Have not tried it with any 2023.1 EAP yet.
