### ISSUE TITLE
Is this plugin dead?

### ISSUE THREAD

**Issue by jeffeld** [vsch/MissingInActions#31]
Hi,

I'm a big fan of MissingInActions but it hasn't worked in WebStorm for about a year now (for me at least). Is it being actively maintained or is it dead/moribund?

No criticism is intended; there can be excellent reasons for when a project's quiet. Just want to know if I should be looking for an alternative if any.

**Comment by j-a-s-o-n-g** [comment]
It is definitely dead. I highly recommend https://github.com/MohammadMD1383/Actionable

**Comment by vsch** [comment]
@jeffeld, not dead but was on life support for a while, as was my desire to keep chasing the JetBrains API for all my plugins. I always loved the IDEs but hated developing/maintaining plugins for it. However, I cannot use any of the IDEs without MIA so it is off life support.

**Uploaded new version which takes care of 2022 compatibility**, works with IJ 2022.1 and CLION 2022.3.2. Have not tried it with any 2023.1 EAP yet.
