### ISSUE TITLE
Add Sort Lines and Multi-Caret Sort Lines

### ISSUE THREAD

**Issue by vsch** [vsch/MissingInActions#7]
### Sort Lines and Multi-Caret Sort Lines

* [ ] if the file has no selection do nothing
* [ ] if the file has a selection then sort the lines in the selection based on text, with option to ignore indent blanks.
* [ ] When sorting preserve the last line's `,`, `;` or none of these endings based on what is the
  ending of the last line before the sort. That way lists of collections and enum values can be
  sorted without needing to edit.
* [ ] Handle multi-carets by sorting lines based on caret position and whether it has a selection:
    * [ ] lines with carets that have selections are sorted on the selection contents
    * [ ] lines with carets but no selection sorted on text after caret position, with option to not
      sort them but just group together.
    * [ ] lines without carets go to end of the list (sorted or unsorted as an option)
    * [ ] if lines with and without carets are sorted then any blank lines in that set are removed.
* [ ] have an options popup version of the action that will remember its last settings for use
  without popup or just use this once.

**Comment by krasa** [comment]
A lot of it is already done in https://github.com/krasa/StringManipulation

**Comment by vsch** [comment]
@krasa, thanks for pointing it out. I use your StringManipulation all the time but not use it for sorting. Didn't look for the functionality there. 😊 

I use LineSorter that I modified to preserve the line ending on the last line before sorting so that sorting the contents of a list definition will not have to be edited after sorting, as in:

```
listOf(
def,
xyz,
abc
);
```

to get:

```
listOf(
abc,
def,
xyz
);
```

Your sorting is great, I just checked it out.

I can just detect if StringManipulation is installed and only add a pop-up pane for options similar to in place variable refactoring used by the IDE. I have to add this style of pop-up for other functionality so this would be a good choice instead of duplicating what you already have done well.

In the end this plugin on my system will always be installed with StringManipulation. 😁

**Comment by krasa** [comment]
So I implemented that preserving and ignoring of whitespaces... now I just need to properly test it all before releasing...

![image](https://cloud.githubusercontent.com/assets/1160875/21747045/8cd97340-d55a-11e6-8c1a-4d4be5605ee0.png)

(The dialog is displayed upon every execution and persisted.)

**Comment by vsch** [comment]
@krasa, looks good. Now testing is the hardest part because of all the modalities in the IDE. If you make a pre-release available for download I can do some testing. It can't hurt.

**Comment by krasa** [comment]
I had to make some small ugly changes for IJ 2017... but that should all be fine, the real problem was the actual logic for preserving those characters - particulary how to handle whitespaces...

You can take a look at how it transforms particular lines, hopefully I did not miss any edge cases...
The format is: `original line | new line | transformed result` (what is in brackets is the actual string)
https://github.com/krasa/StringManipulation/blob/4184b996079cc16c8e7f40bc8a4262f59ca4eca9/test/osmedile/intellij/stringmanip/sort/support/SortLineTest.java#L99-L99 

Build:
https://github.com/krasa/StringManipulation/releases/download/5.3.143.000.1/StringManipulation.jar

**Comment by vsch** [comment]
@krasa, thank you. I will try it out and provide feedback in your repo Issues to make it all proper.

I am not sure if I follow the test cases but it appears to me you went further than necessary in preserving the line endings because it is only possible to preserve line endings if all the lines have an ending or lack of it and the last line has something else. Lets say: all lines have `,` except for the last line. 

Then after sorting all lines except the last one should have `,`. Similarly if all lines have `,` and last line has `;` then the same should happen after sorting. I would ignore whitespace surrounding the `,`, `;` or any other line ending sequence that is preserved so that <code style="whitespace:pre">"     ,    "</code> is the same as `","` for purposes of recognizing that a line has a particular ending.

In all other cases, where all lines except last are not the same, then no conclusion can be made about the pattern of endings and no adjustments are done after sorting.

After sorting if all vs. last line pattern was detected then any line before last that does not have a matching ending has its ending removed/added/replaced depending on what the common ending pattern is. 

Same for the last line after sorting, with its ending changed if it does not match the last line ending before sort.

So after sorting you will have at most 2 lines whose endings will be adjusted: last line before sort moving to non-last line position and non-last line before sort moving to last line position. The rest of the lines will not be changed in any way. This is probably the best scenario since it is very hard to predict user desired formatting. This way, even if you get it wrong the user will only have to adjust edit two lines instead of all lines.

I will test it out and see how it performs on real lists. I always find it very difficult to see how code should behave without playing with an actual implementation on real text. I find when it comes to text processing there are so many possibilities that, for me at least, they are hard to imagine but will pop up in real life usage.

**Comment by krasa** [comment]
I maybe made it a little bit more universal and simple. [It was just a few lines of code...](https://github.com/krasa/StringManipulation/blob/759a73e4efd9d9a28aee2e68e8e1ffd8dd4e6058/src/osmedile/intellij/stringmanip/sort/support/SortLine.java#L58-L64)
It preserves line endings no matter what, so then it is your problem what you are actually doing. 

After sorting, each line's ending is adjusted by the original line's trailing characters. 
And since I really don't know what the user is doing, I preserve the whitespaces. 

So as you can see, my test cases are mainly about transforming one line to another and how it affects whitespaces, since I do not want to change those lines more than necessary.

**Comment by krasa** [comment]
Here is a fixed version, I don't know how it could have worked before :] https://github.com/krasa/StringManipulation/releases/download/5.3.143.000.2/StringManipulation.jar

**Comment by vsch** [comment]
@krasa, I tried your last version and it works very well. I will make it my default sort short cut so I can exercise it in real conditions.

As for how it could work before, you would be surprised how much accidentally working code is out there. I am constantly surprised when I find a bug in my code, how it appeared to be working for most use cases.

Great job on the sort. 

Here are some ideas:

You may want to combine all the Sort actions, Sort Lines, Reverse, Shuffle and Sort by subselection into launching the same dialog but with different default Sort Action pre-selected. The action choice is not persisted when the dialog is closed. This would allow the user to change their mind on the sort action after the dialog is opened and give all the preservation power of your Sort Lines to the other "Sort" actions.

You are providing a complete assortment of sorting options, if you make them orthogonal with respect to line ending preservation then it will its use very intuitive and flexible under all circumstances.

Definitely a thumbs up on your implementation of sort with line preservation.

**Comment by vsch** [comment]
@krasa, just updated to latest StringManipulation. AWESOME!! Thanks
