### ISSUE TITLE
Unindent selected line expands selection to start of document

### ISSUE THREAD

**Issue by paiv** [vsch/MissingInActions#9]
When I'm in this state:

<img width="219" alt="screen1" src="https://cloud.githubusercontent.com/assets/196601/20644709/a173f836-b447-11e6-957b-b2fe777634e5.png">

and press Shift+Tab (Unindent Line or Selection)

selection changes to this:

<img width="219" alt="screen2" src="https://cloud.githubusercontent.com/assets/196601/20644714/c82b62a2-b447-11e6-9f46-ba130c226468.png">

---
Missing In Actions Version: 0.7.0

PyCharm Community Edition 2016.3
Build #PC-163.8233.8, built on November 22, 2016
JRE: 1.8.0_112-release-408-b2 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o

macOS Sierrra 10.12.1 (16B2555)

<img width="776" alt="prefs" src="https://cloud.githubusercontent.com/assets/196601/20644716/deccb8c6-b447-11e6-8a88-f2adc6eab271.png">

**Comment by vsch** [comment]
@paiv, thank you I'll fix it.  As a workaround, you can disable auto line mode all together. You still get the word navigation actions and other "selectable" non-line mode options.

**Comment by paiv** [comment]
@vsch that worked. Thank you.
